const actionTypes = {
    INPUT_VALUE: 'INPUT_VALUE',
    FETCH_POKEMON_REQUEST: 'FETCH_POKEMON_REQUEST',
    FETCH_POKEMON_SUCCESS: 'FETCH_POKEMON_SUCCESS',
    FETCH_POKEMON_FAILURE: 'FETCH_POKEMON_FAILURA'
}

export { actionTypes }