const actionTypes = {
    SEARCH_TYPE_NAME: 'SEARCH_TYPE_NAME',
    SEARCH_TYPE_SKILLS: 'SEARCH_TYPE_SKILLS',
    INPUT_VALUE: 'INPUT_VALUE',
    FETCH_POKEMON_REQUEST: 'FETCH_POKEMON_REQUEST',
    FETCH_POKEMON_SUCCESS: 'FETCH_POKEMON_SUCCESS',
    FETCH_POKEMON_FAILURE: 'FETCH_POKEMON_FAILURE',
    FETCH_ABILITY_REQUEST: 'FETCH_ABILITY_REQUEST',
    FETCH_ABILITY_SUCCESS: 'FETCH_ABILITY_SUCCESS',
    FETCH_ABILITY_FAILURE: 'FETCH_ABILITY_FAILURE',
}

export { actionTypes }